const plugin = require('tailwindcss/plugin');

/**
 * Semantic theme tokens for easier white-labeling.
 * Keep these mapped to current brand values so existing UI remains unchanged.
 */
const THEME_TOKENS = {
  brand: {
    primary: '#008BCC',
    primaryHover: '#00628F',
    primarySoft: '#EBF9FF',
    secondary: '#009DE6',
    accent: '#1C959B',
    accentSoft: '#CBF3F6',
    accentStrong: '#75E0E6',
  },
  text: {
    heading: '#001929',
    body: '#00263E',
    muted: '#475467',
    inverse: '#FFFFFF',
  },
  surface: {
    page: '#F2F4F7',
    panel: '#FFFFFF',
    warm: '#FEFAE7',
  },
  state: {
    danger: '#F68DA7',
    interactiveHover: '#F6F6F6',
    interactiveText: '#041227',
    focusRing: '#1C959B',
  },
  shape: {
    fieldRadius: '4px',
    cardRadius: '16px',
    pillRadius: '100px',
  },
  size: {
    touchTarget: '44px',
    formField: '52px',
  },
  font: {
    primary: 'Public Sans',
    montserrat: 'Montserrat',
    comfortaa: 'Comfortaa',
  },
};

module.exports = {
  mode: 'jit',
  content: [
    './*.php',
    './acf-fields/**/*.php',
    './inc/**/*.php',
    './template-parts/**/*.php',
    './woocommerce/**/*.php',
    './assets/js/**/*.js',
    '../plugins/matrix-donations/**/*.php',
    '../plugins/matrix-donations/assets/js/**/*.js',
  ],
  theme: {
    extend: {
      fontFamily: {
        primary: [`var(--font-primary, '${THEME_TOKENS.font.primary}')`, 'sans-serif'],
        secondary: ['Playfair', 'serif'],
        montserrat: [`var(--font-montserrat, '${THEME_TOKENS.font.montserrat}')`, 'sans-serif'],
        comfortaa: [`var(--font-comfortaa, '${THEME_TOKENS.font.comfortaa}')`, 'sans-serif'],
      },
      colors: {
        slate: {
          DEFAULT: '#001929',
          900: '#001929',
        },
        sky: {
          DEFAULT: '#00263E',
          800: '#00628F',
          950: '#00263E',
        },
        red: { 
          DEFAULT: '#F68DA7',
        },
        primary: {
          DEFAULT: '#009DE6',
          light: '#EBF9FF',
        },
        secondary: {
          DEFAULT: '#FCF4C5',
        },
        tertiary: {
          DEFAULT: '#00263E',
        },
        background: {
          DEFAULT: '#F2F4F7',
          light: '#EBF9FF',
          dark: '#000000',
        },
        highlight: {
          primary: '#101828',
          secondary: '#041227',
          light: '#FFF9E2',
        },
        text: {
          primary: '#1D2939',
          secondary: '#ffffff',
          accent: '#1D2939',
        },
        hover: {
          bg: '#F6F6F6', // Using primary-light as hover background
          text: '#000', // Using accent-greenDark as hover text
        },
        /**
         * Semantic aliases for future site duplication/re-skinning.
         * These are additive only; existing color keys stay intact.
         */
        brand: {
          primary: `var(--color-brand-primary, ${THEME_TOKENS.brand.primary})`,
          'primary-hover': `var(--color-brand-primary-hover, ${THEME_TOKENS.brand.primaryHover})`,
          'primary-soft': `var(--color-brand-primary-soft, ${THEME_TOKENS.brand.primarySoft})`,
          secondary: `var(--color-brand-secondary, ${THEME_TOKENS.brand.secondary})`,
          accent: `var(--color-brand-accent, ${THEME_TOKENS.brand.accent})`,
          'accent-soft': `var(--color-brand-accent-soft, ${THEME_TOKENS.brand.accentSoft})`,
          'accent-strong': `var(--color-brand-accent-strong, ${THEME_TOKENS.brand.accentStrong})`,
        },
        content: {
          heading: `var(--color-content-heading, ${THEME_TOKENS.text.heading})`,
          body: `var(--color-content-body, ${THEME_TOKENS.text.body})`,
          muted: `var(--color-content-muted, ${THEME_TOKENS.text.muted})`,
          inverse: `var(--color-content-inverse, ${THEME_TOKENS.text.inverse})`,
        },
        surface: {
          page: `var(--color-surface-page, ${THEME_TOKENS.surface.page})`,
          panel: `var(--color-surface-panel, ${THEME_TOKENS.surface.panel})`,
          warm: `var(--color-surface-warm, ${THEME_TOKENS.surface.warm})`,
        },
        state: {
          danger: `var(--color-state-danger, ${THEME_TOKENS.state.danger})`,
          'interactive-hover': `var(--color-state-interactive-hover, ${THEME_TOKENS.state.interactiveHover})`,
          'interactive-text': `var(--color-state-interactive-text, ${THEME_TOKENS.state.interactiveText})`,
          focus: `var(--color-state-focus, ${THEME_TOKENS.state.focusRing})`,
        },
      },
      backgroundColor: {
        'hover': '#F6F6F6', // Now available as hover:bg-hover-bg
      },
      textColor: {
        'hover': '#041227', // Now available as hover:text-hover-text
      },
      fontSize: {
        'xs': '14px',
        base: '16px',
        wp_editor_p: '20px',
      },
      width: {
        'container-md': '1084px',
        'container-lg': '1280px',
        'container': '1280px',
      },
      maxWidth: {
        'container': '70rem',
        'xxs': '320px',
        'xs': '480px',
        'mob': '575px',
        'sm': '640px',
        'md': '768px',
        'tab': '1024px',
        'lg': '1200px',
        'xl': '1280px',
        'xxl': '1440px',
        'ultrawide': '1920px',
      },
      borderRadius: {
        'custom': '0px',
        'custom-sm': '4px',
        'custom-md': '8px',
        'custom-lg': '16px',
        'custom-xl': '40px',
        'custom-full': '100%',
        'btn': '0px',
        'field': `var(--radius-field, ${THEME_TOKENS.shape.fieldRadius})`,
        'card': `var(--radius-card, ${THEME_TOKENS.shape.cardRadius})`,
        'pill': `var(--radius-pill, ${THEME_TOKENS.shape.pillRadius})`,
      },
      minHeight: {
        touch: `var(--size-touch-target, ${THEME_TOKENS.size.touchTarget})`,
        field: `var(--size-form-field, ${THEME_TOKENS.size.formField})`,
      },
      minWidth: {
        touch: `var(--size-touch-target, ${THEME_TOKENS.size.touchTarget})`,
      },
      boxShadow: {
        'focus-brand': `0 0 0 3px var(--color-state-focus, ${THEME_TOKENS.state.focusRing})`,
        'focus-brand-strong': `0 0 0 4px var(--color-state-focus, ${THEME_TOKENS.state.focusRing})`,
      },
      animation: {
        'scroll300': 'scroll 300s linear infinite',
      },
      keyframes: {
        scroll: {
          '0%': { transform: 'translateX(0)' },
          '100%': { transform: 'translateX(-100%)' },
        },
      },
    },
    screens: {
      xxs: '320px',
      xs: '480px',
      mob: '575px',
      sm: '640px',
      md: '768px',
      tab: '993px', 
      lg: '1084px',
      xl: '1280px',
      xxl: '1440px',
      ultrawide: '1920px',
    },
    container: {
      center: true,
      padding: '1.5rem',
      screens: {
        xxs: '320px',
        xs: '480px',
        mob: '575px',
        sm: '640px',
        md: '768px',
        lg: '1024px',
        xl: '1280px',
        xxl: '1480px',
        ultrawide: '1920px',
      },
    },
  },
  variants: {
    extend: {
      backgroundColor: ['not-first'],
      display: ['before', 'after'],
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/typography'),
    require('tailwindcss-pseudo')({
      empty: true,
      before: true,
      after: true,
    }),
    plugin(function ({ addUtilities, addVariant }) {
      addVariant('hocus', ['&:hover', '&:focus-visible']);

      addUtilities({
        '.a11y-focus': {
          outline: 'none',
        },
        '.a11y-focus:focus-visible': {
          boxShadow: `0 0 0 3px var(--color-state-focus, ${THEME_TOKENS.state.focusRing})`,
          outline: 'none',
        },
        '.tap-target': {
          minWidth: `var(--size-touch-target, ${THEME_TOKENS.size.touchTarget})`,
          minHeight: `var(--size-touch-target, ${THEME_TOKENS.size.touchTarget})`,
        },
      });
    }),
  ],
  safelist: [
    'md:gap-6',
    'md:gap-10',
    'aspect-[4/3]',
    'left-[-25px]',
    'w-[calc(100%+50px)]',
    'border-t-[6px]',
    'border-b-[6px]',
    'border-r-[6px]',
    'border-l-[6px]',
    'bg-opacity-90',
    'group-hover:bg-[#041227]',
    'group-focus-within:bg-[#041227]',
    'focus-visible:bg-[#041227]',
    'md:col-span-1',
    'md:col-span-2',
    'md:col-span-3',
    'md:col-span-4',
    'md:col-span-6',
    'md:col-span-8',
    'md:col-span-12',
    'lg:col-span-1',
    'lg:col-span-2',
    'lg:col-span-3',
    'lg:col-span-4',
    'lg:col-span-6',
    'lg:col-span-8',
    'lg:col-span-12',
    'col-span-1',
    'col-span-2',
    'col-span-3',
    'col-span-4',
    'col-span-6',
    'col-span-8',
    'col-span-12',
    'hover:bg-hover',
    'hover:text-hover',
    'bg-hover',
    'text-hover',
    'menu-item',
    'current-menu-item',
    'current-menu-ancestor',
    'current-menu-parent',
    'menu-item-has-children',
    'opacity-0',
    'opacity-100',
    'pointer-events-auto',
    'transition-opacity',
    'duration-500',
    'duration-700',
    'absolute',
    'relative',
    'top-0',
    'left-0',
    'right-0',
    'bottom-0',
    'inset-0',
    'max-w-[745px]',
    'fit-content',
    'pt-0',
    'pt-1',
    'pt-2',
    'pt-3',
    'pt-4',
    'pt-5',
    'pb-0',
    'pb-1',
    'pb-2',
    'pb-3',
    'pb-4',
    'pb-5',
    'pl-4',
    'pr-4',
    'pl-5',
    'pr-5',
    'pl-6',
    'pr-6',
    'pl-7',
    'pr-7',
    'pl-8',
    'pr-8',
    'pl-9',
    'pr-9',
    'mb-4',
    'mb-5',
    'mb-6',
    'mb-7',
    'mb-8',
    'pl-10',
    'pr-10',
    'w-1/2',
    'w-1/3',
    'w-2/3',
    'w-1/4',
    'w-2/4',
    'w-3/4',
    'w-1/5',
    'w-2/5',
    'w-3/5',
    'w-4/5',
    'w-1/6',
    'w-2/6',
    'w-3/6',
    'w-4/6',
    'w-5/6',
    'w-1/12',
    'w-2/12',
    'w-3/12',
    'w-4/12',
    'w-5/12',
    'w-6/12',
    'w-7/12',
    'w-8/12',
    'w-9/12',
    'w-10/12',
    'w-11/12',
    'w-full',
    // Container classes
    'container',
    'container-md',
    'max-w-container',
    'max-w-container-md',
    'max-w-container-lg',
    'max-w-xxs',
    'max-w-xs',
    'max-w-mob',
    'max-w-sm',
    'max-w-md',
    'max-w-lg',
    'max-w-xl',
    'max-w-xxl',
    'max-w-ultrawide',
    'rounded-b-none',
    'rounded-l-lg',
    'rounded-r-lg',
    'md:rounded-l-lg',
    'md:rounded-r-lg',
    'rounded-t-lg',
    'md:rounded-t-none',
    'grid-cols-1',
    'grid-cols-2',
    'grid-cols-3',
    'sm:grid-cols-1',
    'sm:grid-cols-2',
    'sm:grid-cols-3',
    'lg:grid-cols-1',
    'lg:grid-cols-2',
    'lg:grid-cols-3',
    'grid-cols-4',
    'grid-cols-5',
    'grid-cols-6',
    'grid-cols-7',
    'grid-cols-8',
    'grid-cols-9',
    'grid-cols-10',
    'grid-cols-11',
    'grid-cols-12',
    'max-sm:grid-cols-1',
    'max-sm:grid-cols-2',
    'max-sm:grid-cols-3',
   
    ...Array.from({ length: 101 }, (_, i) => `p-[${i + 1}rem]`),
    ...Array.from({ length: 101 }, (_, i) => `px-[${i + 1}rem]`),
    ...Array.from({ length: 101 }, (_, i) => `py-[${i + 1}rem]`),
    ...Array.from({ length: 101 }, (_, i) => `pt-[${i + 1}rem]`),
    ...Array.from({ length: 101 }, (_, i) => `pb-[${i + 1}rem]`),
    ...Array.from({ length: 101 }, (_, i) => `pl-[${i + 1}rem]`),
    ...Array.from({ length: 101 }, (_, i) => `pr-[${i + 1}rem]`),
    // Dynamic padding classes devices
    ...Array.from({ length: 101 }, (_, i) => `xs:p-[${i + 1}rem]`),
    ...Array.from({ length: 101 }, (_, i) => `xs:px-[${i + 1}rem]`),
    ...Array.from({ length: 101 }, (_, i) => `xs:py-[${i + 1}rem]`),
    ...Array.from({ length: 101 }, (_, i) => `xs:pt-[${i + 1}rem]`),
    ...Array.from({ length: 101 }, (_, i) => `xs:pb-[${i + 1}rem]`),
    ...Array.from({ length: 101 }, (_, i) => `xs:pl-[${i + 1}rem]`),
    ...Array.from({ length: 101 }, (_, i) => `xs:pr-[${i + 1}rem]`),
    //mob
    ...Array.from({ length: 101 }, (_, i) => `mob:p-[${i + 1}rem]`),
    ...Array.from({ length: 101 }, (_, i) => `mob:px-[${i + 1}rem]`),
    ...Array.from({ length: 101 }, (_, i) => `mob:py-[${i + 1}rem]`),
    ...Array.from({ length: 101 }, (_, i) => `mob:pt-[${i + 1}rem]`),
    ...Array.from({ length: 101 }, (_, i) => `mob:pb-[${i + 1}rem]`),
    ...Array.from({ length: 101 }, (_, i) => `mob:pl-[${i + 1}rem]`),
    ...Array.from({ length: 101 }, (_, i) => `mob:pr-[${i + 1}rem]`),
    //sm
    ...Array.from({ length: 101 }, (_, i) => `sm:p-[${i + 1}rem]`),
    ...Array.from({ length: 101 }, (_, i) => `sm:px-[${i + 1}rem]`),
    ...Array.from({ length: 101 }, (_, i) => `sm:py-[${i + 1}rem]`),
    ...Array.from({ length: 101 }, (_, i) => `sm:pt-[${i + 1}rem]`),
    ...Array.from({ length: 101 }, (_, i) => `sm:pb-[${i + 1}rem]`),
    ...Array.from({ length: 101 }, (_, i) => `sm:pl-[${i + 1}rem]`),
    ...Array.from({ length: 101 }, (_, i) => `sm:pr-[${i + 1}rem]`),
    //md
    ...Array.from({ length: 101 }, (_, i) => `md:p-[${i + 1}rem]`),
    ...Array.from({ length: 101 }, (_, i) => `md:px-[${i + 1}rem]`),
    ...Array.from({ length: 101 }, (_, i) => `md:py-[${i + 1}rem]`),
    ...Array.from({ length: 101 }, (_, i) => `md:pt-[${i + 1}rem]`),
    ...Array.from({ length: 101 }, (_, i) => `md:pb-[${i + 1}rem]`),
    ...Array.from({ length: 101 }, (_, i) => `md:pl-[${i + 1}rem]`),
    ...Array.from({ length: 101 }, (_, i) => `md:pr-[${i + 1}rem]`),
    //lg
    ...Array.from({ length: 101 }, (_, i) => `lg:p-[${i + 1}rem]`),
    ...Array.from({ length: 101 }, (_, i) => `lg:px-[${i + 1}rem]`),
    ...Array.from({ length: 101 }, (_, i) => `lg:py-[${i + 1}rem]`),
    ...Array.from({ length: 101 }, (_, i) => `lg:pt-[${i + 1}rem]`),
    ...Array.from({ length: 101 }, (_, i) => `lg:pb-[${i + 1}rem]`),
    ...Array.from({ length: 101 }, (_, i) => `lg:pl-[${i + 1}rem]`),
    ...Array.from({ length: 101 }, (_, i) => `lg:pr-[${i + 1}rem]`),
    //xl
    ...Array.from({ length: 101 }, (_, i) => `xl:p-[${i + 1}rem]`),
    ...Array.from({ length: 101 }, (_, i) => `xl:px-[${i + 1}rem]`),
    ...Array.from({ length: 101 }, (_, i) => `xl:py-[${i + 1}rem]`),
    ...Array.from({ length: 101 }, (_, i) => `xl:pt-[${i + 1}rem]`),
    ...Array.from({ length: 101 }, (_, i) => `xl:pb-[${i + 1}rem]`),
    ...Array.from({ length: 101 }, (_, i) => `xl:pl-[${i + 1}rem]`),
    ...Array.from({ length: 101 }, (_, i) => `xl:pr-[${i + 1}rem]`),
    //xxl
    ...Array.from({ length: 101 }, (_, i) => `xxl:p-[${i + 1}rem]`),
    ...Array.from({ length: 101 }, (_, i) => `xxl:px-[${i + 1}rem]`),
    ...Array.from({ length: 101 }, (_, i) => `xxl:py-[${i + 1}rem]`),
    ...Array.from({ length: 101 }, (_, i) => `xxl:pt-[${i + 1}rem]`),
    ...Array.from({ length: 101 }, (_, i) => `xxl:pb-[${i + 1}rem]`),
    ...Array.from({ length: 101 }, (_, i) => `xxl:pl-[${i + 1}rem]`),
    ...Array.from({ length: 101 }, (_, i) => `xxl:pr-[${i + 1}rem]`),
    //ultrawide
    ...Array.from({ length: 101 }, (_, i) => `ultrawide:p-[${i + 1}rem]`),
    ...Array.from({ length: 101 }, (_, i) => `ultrawide:px-[${i + 1}rem]`),
    ...Array.from({ length: 101 }, (_, i) => `ultrawide:py-[${i + 1}rem]`),
    ...Array.from({ length: 101 }, (_, i) => `ultrawide:pt-[${i + 1}rem]`),
    ...Array.from({ length: 101 }, (_, i) => `ultrawide:pb-[${i + 1}rem]`),
    ...Array.from({ length: 101 }, (_, i) => `ultrawide:pl-[${i + 1}rem]`),
    ...Array.from({ length: 101 }, (_, i) => `ultrawide:pr-[${i + 1}rem]`),
    // Dynamic border classes
    ...Array.from({ length: 101 }, (_, i) => `border-[${i}px]`),
    ...Array.from({ length: 101 }, (_, i) => `border-t-[${i}px]`),
    ...Array.from({ length: 101 }, (_, i) => `border-b-[${i}px]`),
    ...Array.from({ length: 101 }, (_, i) => `border-l-[${i}px]`),
    ...Array.from({ length: 101 }, (_, i) => `border-r-[${i}px]`),
    // text size
    ...Array.from({ length: 101 }, (_, i) => `text-[${i}px]`),
    // text size for devices
    ...Array.from({ length: 101 }, (_, i) => `xs:text-[${i}px]`),
    ...Array.from({ length: 101 }, (_, i) => `mob:text-[${i}px]`),
    ...Array.from({ length: 101 }, (_, i) => `sm:text-[${i}px]`),
    ...Array.from({ length: 101 }, (_, i) => `md:text-[${i}px]`),
    ...Array.from({ length: 101 }, (_, i) => `lg:text-[${i}px]`),
    ...Array.from({ length: 101 }, (_, i) => `xl:text-[${i}px]`),
    ...Array.from({ length: 101 }, (_, i) => `xxl:text-[${i}px]`),
    ...Array.from({ length: 101 }, (_, i) => `ultrawide:text-[${i}px]`),
    // text size for rem
    ...Array.from({ length: 101 }, (_, i) => `text-[${i}rem]`),
    // text size for devices
    ...Array.from({ length: 101 }, (_, i) => `xs:text-[${i}rem]`),
    ...Array.from({ length: 101 }, (_, i) => `mob:text-[${i}rem]`),
    ...Array.from({ length: 101 }, (_, i) => `sm:text-[${i}rem]`),
    ...Array.from({ length: 101 }, (_, i) => `md:text-[${i}rem]`),
    ...Array.from({ length: 101 }, (_, i) => `lg:text-[${i}rem]`),
    ...Array.from({ length: 101 }, (_, i) => `xl:text-[${i}rem]`),
    ...Array.from({ length: 101 }, (_, i) => `xxl:text-[${i}rem]`),
    ...Array.from({ length: 101 }, (_, i) => `ultrawide:text-[${i}rem]`),
    // text size for em
    ...Array.from({ length: 101 }, (_, i) => `text-[${i}em]`),
    // text size for devices
    ...Array.from({ length: 101 }, (_, i) => `xs:text-[${i}em]`),
    ...Array.from({ length: 101 }, (_, i) => `mob:text-[${i}em]`),
    ...Array.from({ length: 101 }, (_, i) => `sm:text-[${i}em]`),
    ...Array.from({ length: 101 }, (_, i) => `md:text-[${i}em]`),
    ...Array.from({ length: 101 }, (_, i) => `lg:text-[${i}em]`),
    ...Array.from({ length: 101 }, (_, i) => `xl:text-[${i}em]`),
    ...Array.from({ length: 101 }, (_, i) => `xxl:text-[${i}em]`),
    ...Array.from({ length: 101 }, (_, i) => `ultrawide:text-[${i}em]`),
    // dynamic arbitrary color classes
    ...Array.from({ length: 101 }, (_, i) => `text-color-[${i}]`),
    ...Array.from({ length: 101 }, (_, i) => `bg-color-[${i}]`),
    // line height
    ...Array.from({ length: 101 }, (_, i) => `line-height-[${i}]`),
    // line height for devices
    ...Array.from({ length: 101 }, (_, i) => `xs:line-height-[${i}]`),
    ...Array.from({ length: 101 }, (_, i) => `mob:line-height-[${i}]`),
    ...Array.from({ length: 101 }, (_, i) => `sm:line-height-[${i}]`),
    ...Array.from({ length: 101 }, (_, i) => `md:line-height-[${i}]`),
    ...Array.from({ length: 101 }, (_, i) => `lg:line-height-[${i}]`),
    ...Array.from({ length: 101 }, (_, i) => `xl:line-height-[${i}]`),
    ...Array.from({ length: 101 }, (_, i) => `xxl:line-height-[${i}]`),
    ...Array.from({ length: 101 }, (_, i) => `ultrawide:line-height-[${i}]`),
  ],
};
